### ISSUE TITLE
Compiling the UI

### ISSUE THREAD

**Issue by jacksgt** [heinervdm/nohands#7]
Hello,

I'm currently trying to compile HFP, but I'm struggeling with finding the necessary dependencies.
I have installed (on my ArchLinux system):
```
base-devel
qt4
qt5
bluez
bluez-libs
```
I ran `./autogen.sh`, then `./configure` and finally `make`
[Make Output](http://pastebin.com/SGae55Rf)
The problem apparently was that `/usr/lib/qt/bin/uic3` is missing.
Since I had another `uic3` on my system, I created a symlink: 
`ln -s /usr/lib/qt4/bin/uic3 /usr/lib/qt/bin/uic3`    

Unfortunately, that didn't work either:
[Make Output](http://pastebin.com/86Zk5Bzr) (lots and lots of errors)

Am I still missing a dependency?

**Comment by heinervdm** [comment]
I've never tried to compile it with Qt5, and it seems that you are using the moc of Qt5 to compile it.
Can you try to use the Qt4 moc instead?

**Comment by jacksgt** [comment]
If you can tell me how to do that :-D What does `Qt moc` even stand for?

**Comment by heinervdm** [comment]
I've created a new branch qt4-gui, where i've commited a version where i've ported the UI to Qt4.
It compiles now, but i've no idea if it's still working as I have no bluetooth to test it at the moment

**Comment by jacksgt** [comment]
Thank you very much for your work!
Now, I'm getting the following error while compiling:
```
/usr/bin/moc events-qt.h -o events-qt.moc
g++ -DHAVE_CONFIG_H -I. -I..  -I../include -include config.h -DQT_SHARED -DQT3_SUPPORT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtCore    -g  -Wall -MT hfstandalone.o -MD -MP -MF .deps/hfstandalone.Tpo -c -o hfstandalone.o hfstandalone.cpp
In file included from nohandswidget.h:5:0,
                 from hfstandalone.cpp:15:
./nohands.h:13:29: fatal error: QtWidgets/QAction: No such file or directory
compilation terminated.
Makefile:497: recipe for target 'hfstandalone.o' failed
make[2]: *** [hfstandalone.o] Error 1
make[2]: Leaving directory '/tmp/nohands/qt'
Makefile:528: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/nohands'
Makefile:459: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by heinervdm** [comment]
This is strange, because that file is created by your uic, and it's putting there the wrong path to QAction.
As a workaround you can modify this qt/nohands.h and replace #include <QtWidgets/QAction> with #include <QAction>

**Comment by heinervdm** [comment]
Another workaround could be to do define export UIC and MOC shell variables before running ./configure.
And set them to the Qt4 version, they are probably called uic-qt4 and moc-qt4 or similar.

**Comment by heinervdm** [comment]
I also commited a new version of configure.ac which should look for these names first before trying uic and moc

**Comment by jacksgt** [comment]
Dude, hold on, hold on, you're fast! :D 

Your first suggestion did not work, that was kind of a mess.
However the second one did:
```bash
./autogen.sh
export UIC="/usr/bin/uic-qt4"
export MOC="/usr/bin/moc-qt4"
./configure
make
```

EDIT:
Yes, it also works with the latest version of `configure.ac` - awesome and thank you!
